-- MySQL Script generated by MySQL Workbench
-- 02/21/16 21:07:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema grupo_inn_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grupo_inn_db` DEFAULT CHARACTER SET utf8 ;
USE `grupo_inn_db` ;

-- -----------------------------------------------------
-- Table `grupo_inn_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_inn_db`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_inn_db`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_inn_db`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `f_nacimiento` DATE NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `url_imagen` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPerfil`, `Usuario_idUsuario`),
  INDEX `fk_Perfil_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Perfil_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `grupo_inn_db`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_inn_db`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_inn_db`.`Evento` (
  `idEvento` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TINYTEXT NULL,
  `url_imagen` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `lugar` VARCHAR(45) NULL,
  `cupo_max` INT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_inn_db`.`Evento_has_Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_inn_db`.`Evento_has_Perfil` (
  `Evento_idEvento` INT NOT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`Evento_idEvento`, `Perfil_idPerfil`),
  INDEX `fk_Evento_has_Perfil_Perfil1_idx` (`Perfil_idPerfil` ASC),
  INDEX `fk_Evento_has_Perfil_Evento1_idx` (`Evento_idEvento` ASC),
  CONSTRAINT `fk_Evento_has_Perfil_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `grupo_inn_db`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Perfil_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `grupo_inn_db`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_inn_db`.`Gusto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_inn_db`.`Gusto` (
  `idGusto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGusto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_inn_db`.`Perfil_has_Gusto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_inn_db`.`Perfil_has_Gusto` (
  `Perfil_idPerfil` INT NOT NULL,
  `Perfil_Usuario_idUsuario` INT NOT NULL,
  `Gusto_idGusto` INT NOT NULL,
  PRIMARY KEY (`Perfil_idPerfil`, `Perfil_Usuario_idUsuario`, `Gusto_idGusto`),
  INDEX `fk_Perfil_has_Gusto_Gusto1_idx` (`Gusto_idGusto` ASC),
  INDEX `fk_Perfil_has_Gusto_Perfil1_idx` (`Perfil_idPerfil` ASC, `Perfil_Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Perfil_has_Gusto_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil` , `Perfil_Usuario_idUsuario`)
    REFERENCES `grupo_inn_db`.`Perfil` (`idPerfil` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_has_Gusto_Gusto1`
    FOREIGN KEY (`Gusto_idGusto`)
    REFERENCES `grupo_inn_db`.`Gusto` (`idGusto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

